# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '13d3a5da-9810-4864-b417-c2b2527baf2f'
  containerRegistry: 'mlmccontainers.azurecr.io'
  # Services
  operationServiceRepository: 'operation-service'
  mgccServiceRepository: 'mgcc-service'
  webspaClientRepository: 'webspa-client'
  # Dockerfiles of the services
  operationServiceDockerfilePath: 'src/Services/Operation/Dockerfile'
  mgccServiceDockerfilePath: 'src/Services/MGCC.Api/Dockerfile'
  webspaClientDockerfilePath: 'src/Services/MGCC.Api/Dockerfile'

  

  tag: '$(Build.BuildId)'
  imagePullSecret: 'mlmccontainers69999e3a-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
# Build Operation Service Image
- stage: Build Operation Service
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(operationServiceRepository)
        dockerfile: $(operationServiceDockerfilePath)
        buildContext: '.'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: manifests
      artifact: manifests
# Deploy Operation Service Image
- stage: Deploy Operation Service
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'kakarotto67mlmc-6929.mlmc'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/operation-deployment.yml
                $(Pipeline.Workspace)/manifests/operation-service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(operationServiceRepository):$(tag)


# Build MGCC Service Image
- stage: Build MGCC Service
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(mgccServiceRepository)
        dockerfile: $(mgccServiceDockerfilePath)
        buildContext: '.'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: manifests
      artifact: manifests
# Deploy MGCC Service Image
- stage: Deploy MGCC Service
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'kakarotto67mlmc-6929.mlmc'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/mgcc-deployment.yml
                $(Pipeline.Workspace)/manifests/mgcc-service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(mgccServiceRepository):$(tag)


# Build WebSpa Client Image
- stage: Build WebSpa Service
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(webspaClientRepository)
        dockerfile: $(webspaClientDockerfilePath)
        buildContext: '.'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: manifests
      artifact: manifests
# Deploy WebSpa Client Image
- stage: Deploy WebSpa Service
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'kakarotto67mlmc-6929.mlmc'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/webspa-deployment.yml
                $(Pipeline.Workspace)/manifests/webspa-service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(webspaClientRepository):$(tag)