version: "3.1"

services:

  operation-service:
    image: "operation-service"
    container_name: "mlmc-operation-service"
    build:
      context: .
      dockerfile: src/Services/Operation/Dockerfile
    ports:
      - "44386:80"
    networks:
      - backend
    environment:
      OperationDatabaseSettings__Host: host.docker.internal
      MessageBusSettings__HostName: message-bus

  mgcc-service:
    image: "mgcc-service"
    container_name: "mlmc-mgcc-service"
    build:
      context: .
      dockerfile: src/Services/MGCC.Api/Dockerfile
    ports:
      - "44316:80"
    networks:
      - backend
    environment:
      MessageBusSettings__HostName: message-bus

  webspa-client:
    image: "webspa-client"
    container_name: "mlmc-webspa-client"
    build:
      context: .
      dockerfile: src/WebSpa/Dockerfile
    ports:
      - "4200:4200"
    networks:
      - backend
    depends_on:
      - "operation-service"
      - "mgcc-service"

networks:
  backend: