version: "3.1"

services:

  operation-database:
    image: "mongo"
    container_name: "mlmc-operation-database"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    ports:
      - "27018:27017"
    networks:
      - backend

  message-bus:
    image: "rabbitmq:3-management"
    container_name: "mlmc-message-bus"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: qwerty
      RABBITMQ_DEFAULT_VHOST: local
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

networks:
  backend: