version: "3"
  
services:
  operation-database:
    image: "mongo"
    container_name: "mlmc-operation-database"
    ports:
      - "27018:27017"
  message-bus:
    image: "rabbitmq"
    container_name: "mlmc-message-bus"
    ports:
      - "5672:5672"