version: "3"

services:
  operation-database:
    image: "mongo"
    container_name: "mlmc-operation-database"
    ports:
      - "27018:27017"

  message-bus:
    image: "rabbitmq:3-management"
    container_name: "mlmc-message-bus"
    ports:
      - "5672:5672"
      - "15672:15672"
