apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mongo-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-service
    spec:
      containers:
        - name: mongo-service
          image: https://index.docker.io/v1/mongo
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "qwerty"
          ports:
          - containerPort: 27017
        - resources:
          limits:
            memory: "64Mi"
            cpu: "250m"