apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: webspa-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webspa-client
    spec:
      containers:
        - name: webspa-client
          image: mlmccontainers.azurecr.io/webspa-client
          ports:
          - containerPort: 4200
        - resources:
          limits:
            memory: "64Mi"
            cpu: "250m"